apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: task-management-values
    namespace: task-management
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true