apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ include "task-management.namespace" . }}
  labels:
    {{- include "task-management.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "task-management.appSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP