{{- if .Values.app.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.appSecretName" . }}
  namespace: {{ include "task-management.namespace" . }}
  labels:
    {{- include "task-management.appLabels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: "mongodb://{{ .Values.mongodb.auth.appUsername }}:{{ .Values.mongodb.auth.appPassword }}@{{ .Values.mongodb.serviceName }}.{{ .Values.namespace.name }}.svc.cluster.local:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.auth.appDatabase }}?authSource={{ .Values.mongodb.auth.appDatabase }}"
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}