{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "task-management.gatewayName" . }}
  namespace: {{ include "task-management.gatewayNamespace" . }}
  labels:
    {{- include "task-management.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ include "task-management.host" . | quote }}
      tls:
        httpsRedirect: true

    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ include "task-management.host" . | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ include "task-management.certificateSecretName" . }}
        minProtocolVersion: TLSV1_2
{{- end }}