{{- if .Values.mongodb.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.mongodbSecretName" . }}
  namespace: {{ include "task-management.namespace" . }}
  labels:
    {{- include "task-management.mongodbLabels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
  MONGO_APP_DATABASE: {{ .Values.mongodb.auth.appDatabase | quote }}
  MONGO_APP_USERNAME: {{ .Values.mongodb.auth.appUsername | quote }}
  MONGO_APP_PASSWORD: {{ .Values.mongodb.auth.appPassword | quote }}
{{- end }}