{{- if .Values.redis.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.redisSecretName" . }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.redis.password | quote }}
{{- end }}